"""first commit

Revision ID: 3f16a9bda155
Revises: 
Create Date: 2024-12-21 12:59:02.368105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f16a9bda155'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('ssn', sa.Text(), nullable=True),
    sa.Column('zipcode', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    op.drop_table('users')
    # ### end Alembic commands ###
